# This script will take a csv generated by BuscaInsiderBuy and generate another 
#  csv with the metrics of the companies.
import pandas as pd
import joroxbrl.secFiles
import joroxbrl.metrics
import csv

date = '2022-11-09'
dataFolder = 'F:\\Users\\Joronoso\\Documents\\Pablo\\pythonScripts\\Investing\\dataFiles\\'
csvFile = dataFolder +'InsiderTrades_'+date+'.csv'

df = pd.read_csv(csvFile)

df = df[(df['comment']!='BEAR: Bank') 
        & (df['comment']!='BEAR: REIT')
        & (df['comment']!='BEAR: Biotechnology')
        & (df['comment']!='BEAR: Fund')
        & (df['comment']!='BEAR: China')
        & (df['comment']!='BEAR: Insurance')
        & (df['comment']!='BEAR: Capital Markets')
        & (df['comment']!='Awards')
        & (df['ticker'].isnull()==False)
        ]

import logging
logging.basicConfig(level=logging.DEBUG)         

globalDict = {} 

for cik in df.cik.unique():
    print(type(cik))
    print('Processing cik '+str(cik))
    try:
        filing = joroxbrl.secFiles.Filing.getLatestFiling(str(cik), '10-K')
    except:
        print('Skipping cik '+str(cik)+'. No 10-K found in local SEC files')
        globalDict[df[ df['cik']==cik ]['issuer'].iloc[0]] = {'error': 'No 10-K found in local SEC files'}
        continue
        
    filing.getFilingUrls()
    if not filing.checkDataFiles():
        print('Skipping cik '+str(cik)+'. No data files were found')
        globalDict[df[ df['cik']==cik ]['issuer'].iloc[0]] = {'error': 'No data files were found'}
        continue
    m = joroxbrl.metrics.MetricCalculator()
    m.genMetrics(filing)
    print(filing.getFilingUrl())
    #print('CONCEPTS:')
    for i in m.concepts.items():
        print(i[0]+':\t'+str(i[1]))
    #print('METRICS:')
    for i in m.metrics.items():
        print(i[0]+':\t'+str(i[1]))
        
    totalDict = dict(m.concepts, **m.metrics)
    globalDict[df[ df['cik']==cik ]['issuer'].iloc[0]] = totalDict

out_df = pd.DataFrame.from_dict(globalDict)
out_df.to_csv(dataFolder+'AnalysisInsiderTrades_'+date+'.csv', quoting=csv.QUOTE_NONNUMERIC)
    
    